name: OF2212
defaults:
  run:
    shell: bash -o pipefail -i {0}
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Tmate debugging session'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/foamscience/jammy-openfoam:v2212
      options: --user openfoam
      env:
        CATCH_TIMEOUT: 120
        FOAM_FOAMUT: /tmp/foamUT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Compile and Test OpenFOAM components
        run: |
          source /usr/lib/openfoam/openfoam2212/etc/bashrc
          mkdir -p $FOAM_USER_LIBBIN
          wmakeLnInclude src/
          wmake src/testlib
          git clone https://github.com/FoamScience/foamUT $FOAM_FOAMUT
          sed -i 's/mpirun/mpirun --oversubscribe/g' $FOAM_FOAMUT/Alltest
          ln -s "$PWD"/tests "$FOAM_FOAMUT/tests/reflectionTests"
          cd $FOAM_FOAMUT || exit 1
          rm -rf tests/exampleTests
          ./Alltest -s
