name: Tests
defaults:
  run:
    shell: bash -o pipefail -i {0}
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Tmate debugging session'
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/foamscience/jammy-openfoam:v2206-gcc13
      options: --user openfoam
      env:
        CATCH_TIMEOUT: 120
        FOAM_FOAMUT: /tmp/foamUT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Compile and Test OpenFOAM components
        run: |
          source /usr/lib/openfoam/openfoam2206/etc/bashrc
          mkdir -p $FOAM_USER_LIBBIN
          wmakeLnInclude src/
          wmake src/testlib
          git clone https://github.com/FoamScience/foamUT $FOAM_FOAMUT
          sed -i 's/mpirun/mpirun --oversubscribe/g' $FOAM_FOAMUT/Alltest
          ln -s "$PWD"/tests "$FOAM_FOAMUT/tests/reflectionTests"
          cd $FOAM_FOAMUT || exit 1
          _REPO_ROOT=$PWD
          ./Alltest --no-parallel -s
