name: Tests
defaults:
  run:
    shell: bash -o pipefail -i {0}
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Tmate debugging session'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CATCH_TIMEOUT: 120
      FOAM_FOAMUT: /tmp/foamUT
      APPTAINERS: /tmp/of_tainers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Install apptainer
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt install -y apptainer

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible  --break-system-packages

      - name: Compile and Test OpenFOAM components
        run: |
          COMMIT_HASH=${{ github.sha }}
          REPO_PATH=$PWD
          git clone https://github.com/FoamScience/openfoam-apptainer-packaging $APPTAINERS
          git clone https://github.com/FoamScience/foamUT $FOAM_FOAMUT
          sed -i 's/- main/- '${COMMIT_HASH}'/' build/config.yaml
          ansible-playbook $APPTAINERS/build.yaml --extra-vars="original_dir=$PWD" --extra-vars="@build/config.yaml"
          sed -i 's/mpirun/mpirun --oversubscribe/g' $FOAM_FOAMUT/Alltest
          ln -s "$PWD"/tests "$FOAM_FOAMUT/tests/reflectionTests"
          cd $FOAM_FOAMUT || exit 1
          rm -rf tests/exampleTests
          apptainer run $REPO_PATH/containers/projects/reflections-${COMMIT_HASH}.sif "./Alltest --no-parallel -s"
